### ISSUE TITLE
Suggestion: English as the main language

### ISSUE THREAD

**Issue by jgcmarins** [luisferrassini/lifeproject#1]
What about using English as the main language? I guess it's a good practice. It's a universal language, it's commonly used by developers and you also can reach more people :smile:

**Comment by luisferrassini** [comment]
Hello! I didn't have time yet to complete the readme. Using english as the main language makes a lot o sense. I'm gonna accept the suggestion. Thank you very much!

**Comment by jgcmarins** [comment]
Great! You can count on me to help you with language and code review :smile:
